find_path(SDL2_IMAGE_INCLUDE_DIRS SDL_image.h
  PATH_SUFFIXES
    SDL2
)
find_library(SDL2_IMAGE_LIBRARIES NAMES "SDL2_image")

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_image
  REQUIRED_VARS SDL2_IMAGE_INCLUDE_DIRS SDL2_IMAGE_LIBRARIES)