find_path(SDL2_TTF_INCLUDE_DIRS SDL_ttf.h
  PATH_SUFFIXES
    SDL2
)
find_library(SDL2_TTF_LIBRARIES NAMES "SDL2_ttf")

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf
  REQUIRED_VARS SDL2_TTF_INCLUDE_DIRS SDL2_TTF_LIBRARIES)